### ISSUE TITLE
cannot import name '__version__' from 'cast_control'

### ISSUE THREAD

**Issue by btbroot** [alexdelorenzo/cast_control#25]
Installed 0.11.8.post0 from PyPi:
```
...:~$ pip install cast_control
Requirement already satisfied: cast_control in ./.local/lib/python3.9/site-packages (0.11.8.post0)
Collecting typing-extensions>=3.10.0.0
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Requirement already satisfied: click<9.0.0,>=8.0.0 in ./.local/lib/python3.9/site-packages (from cast_control) (8.1.5)
Requirement already satisfied: mpris-server<0.5.0,>=0.4.0 in ./.local/lib/python3.9/site-packages (from cast_control) (0.4.2)
Requirement already satisfied: pydbus<0.7.0,>=0.6.0 in ./.local/lib/python3.9/site-packages (from cast_control) (0.6.0)
Requirement already satisfied: daemons<1.4.0,>=1.3.2 in ./.local/lib/python3.9/site-packages (from cast_control) (1.3.2)
Requirement already satisfied: PyChromecast<9.3.0,>=9.2.0 in ./.local/lib/python3.9/site-packages (from cast_control) (9.2.1)
Requirement already satisfied: PyGObject>=3.34.0 in /usr/lib/python3/dist-packages (from cast_control) (3.38.0)
Requirement already satisfied: appdirs<1.5.0,>=1.4.4 in ./.local/lib/python3.9/site-packages (from cast_control) (1.4.4)
Requirement already satisfied: aiopath>=0.5.11 in ./.local/lib/python3.9/site-packages (from cast_control) (0.5.12)
Requirement already satisfied: anyio<4,>=3.2.0 in ./.local/lib/python3.9/site-packages (from aiopath>=0.5.11->cast_control) (3.7.1)
Requirement already satisfied: aiofile<4,>=3.5.0 in ./.local/lib/python3.9/site-packages (from aiopath>=0.5.11->cast_control) (3.8.7)
Requirement already satisfied: caio~=0.9.0 in ./.local/lib/python3.9/site-packages (from aiofile<4,>=3.5.0->aiopath>=0.5.11->cast_control) (0.9.12)
Requirement already satisfied: exceptiongroup in ./.local/lib/python3.9/site-packages (from anyio<4,>=3.2.0->aiopath>=0.5.11->cast_control) (1.1.2)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<4,>=3.2.0->aiopath>=0.5.11->cast_control) (2.10)
Requirement already satisfied: sniffio>=1.1 in ./.local/lib/python3.9/site-packages (from anyio<4,>=3.2.0->aiopath>=0.5.11->cast_control) (1.3.0)
Requirement already satisfied: unidecode<2.0.0,>=1.2.0 in ./.local/lib/python3.9/site-packages (from mpris-server<0.5.0,>=0.4.0->cast_control) (1.3.6)
Requirement already satisfied: emoji<2.0.0,>=1.2.0 in ./.local/lib/python3.9/site-packages (from mpris-server<0.5.0,>=0.4.0->cast_control) (1.7.0)
Requirement already satisfied: casttube>=0.2.0 in ./.local/lib/python3.9/site-packages/casttube-0.2.1-py3.9.egg (from PyChromecast<9.3.0,>=9.2.0->cast_control) (0.2.1)
Requirement already satisfied: zeroconf>=0.25.1 in /usr/lib/python3/dist-packages (from PyChromecast<9.3.0,>=9.2.0->cast_control) (0.26.1)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3/dist-packages (from PyChromecast<9.3.0,>=9.2.0->cast_control) (3.12.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from casttube>=0.2.0->PyChromecast<9.3.0,>=9.2.0->cast_control) (2.25.1)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject>=3.34.0->cast_control) (1.16.2)
Installing collected packages: typing-extensions
Successfully installed typing-extensions-4.7.1
```

Ran the app:
```
...:~$ .local/bin/cast_control 
Traceback (most recent call last):
  File ".../.local/bin/cast_control", line 5, in <module>
    from cast_control.app.cli import cli
  File ".../.local/lib/python3.9/site-packages/cast_control/app/cli.py", line 9, in <module>
    from .. import __version__, __author__, __copyright__,\
ImportError: cannot import name '__version__' from 'cast_control' (unknown location)
```

Indeed, there's literally nothing in the package directory (apart of subdirectories):
```
...:~$ ls .local/lib/python3.9/site-packages/cast_control
app  assets  device
```

Am I missing some magic here?

**Comment by btbroot** [comment]
After a reinstall, the issue is gone
